// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function AddNonVfoxSdk(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AddVfoxToPath():Promise<void>;

export function ApplyEnvironmentImport(arg1:model.EnvironmentImportPlan):Promise<model.EnvironmentImportResult>;

export function CheckAnyPathOverride():Promise<boolean>;

export function CheckCoreUpdate():Promise<model.CoreInfo>;

export function CheckPluginPathOverride(arg1:string):Promise<boolean>;

export function CheckPluginWin11CompatMode(arg1:string):Promise<boolean>;

export function CheckVfoxInPath():Promise<boolean>;

export function CheckWin11CompatMode():Promise<boolean>;

export function DetectSdkPathVersion(arg1:string,arg2:string):Promise<string>;

export function ExportEnvironmentJson():Promise<string>;

export function GetActiveCustomSdk(arg1:string):Promise<string>;

export function GetAddedPlugins():Promise<Array<string>>;

export function GetAllSdks():Promise<Array<model.SdkInfo>>;

export function GetAvailablePlugins():Promise<Array<model.PluginInfo>>;

export function GetCachedSystemSdks():Promise<Array<model.SdkInfo>>;

export function GetCoreInfo():Promise<model.CoreInfo>;

export function GetDownloadPathInfo():Promise<model.DownloadPathInfo>;

export function GetEnvironmentInventory():Promise<model.EnvironmentInventory>;

export function GetEnvironmentStatus():Promise<model.EnvironmentStatusReport>;

export function GetGitHubSourceSettings():Promise<model.GitHubSourceSettings>;

export function GetInstalledSdks():Promise<Array<model.SdkInfo>>;

export function GetNonVfoxSdks():Promise<Record<string, Array<model.SdkInfo>>>;

export function GetNonVfoxSdksMap():Promise<Record<string, Array<model.SdkInfo>>>;

export function GetPlatformInfo():Promise<model.PlatformInfo>;

export function GetProxyGroups():Promise<Array<model.ProxyGroup>>;

export function GetProxyQuickStatus():Promise<model.ProxyQuickStatus>;

export function GetProxyStatus():Promise<model.ProxyStatus>;

export function GetSdkDetail(arg1:string):Promise<model.SdkDetail>;

export function GetVersionPath(arg1:string,arg2:string):Promise<string>;

export function HijackPluginSystemPath(arg1:string):Promise<void>;

export function HijackSystemPath(arg1:string,arg2:string):Promise<void>;

export function ImportProxySubscription(arg1:string):Promise<model.ProxyStatus>;

export function InstallVersion(arg1:string,arg2:string):Promise<void>;

export function ListCoreVersions():Promise<Array<model.CoreRelease>>;

export function OpenEnvironmentDiagnostic():Promise<void>;

export function PlanEnvironmentImport(arg1:boolean):Promise<model.EnvironmentImportPlan>;

export function PlanEnvironmentMigration(arg1:string):Promise<model.MigrationPlan>;

export function PreviewEnvironmentDocument():Promise<model.EnvironmentDocument>;

export function RefreshAvailablePlugins():Promise<Array<model.PluginInfo>>;

export function RemoveNonVfoxSdk(arg1:string,arg2:string):Promise<void>;

export function RemovePlugin(arg1:string):Promise<void>;

export function RemovePluginWithOptions(arg1:string,arg2:string):Promise<void>;

export function RemoveVfoxFromPath():Promise<void>;

export function ResetDownloadPath():Promise<model.DownloadPathInfo>;

export function ResetDownloadPathWithMigration(arg1:boolean):Promise<model.DownloadPathInfo>;

export function RestorePluginSystemPath(arg1:string):Promise<void>;

export function RestoreSystemPath(arg1:string):Promise<void>;

export function RunVfoxCommand(arg1:Array<string>):Promise<string>;

export function RunVfoxWithProgress(arg1:Array<string>):Promise<void>;

export function SaveGitHubSourceSettings(arg1:model.GitHubSourceSettings):Promise<model.GitHubSourceSettings>;

export function ScanSystemSdks():Promise<void>;

export function SearchVersions(arg1:string):Promise<Array<string>>;

export function SelectDownloadPath():Promise<string>;

export function SelectProxyNode(arg1:string,arg2:string):Promise<model.ProxyStatus>;

export function SetCoreAutoUpdate(arg1:boolean):Promise<model.CoreInfo>;

export function SetDownloadPath(arg1:string):Promise<model.DownloadPathInfo>;

export function SetDownloadPathWithMigration(arg1:string,arg2:boolean):Promise<model.DownloadPathInfo>;

export function SetProxyEnabled(arg1:boolean):Promise<model.ProxyStatus>;

export function SetProxyGroup(arg1:string):Promise<model.ProxyStatus>;

export function SetProxyQuickEnabled(arg1:boolean):Promise<model.ProxyQuickStatus>;

export function SwitchCoreVersion(arg1:string):Promise<model.CoreInfo>;

export function TestProxyGroupDelay(arg1:string):Promise<Array<model.ProxyGroup>>;

export function TestProxyNodeDelay(arg1:string):Promise<model.ProxyNode>;

export function TestProxyQuickDelay():Promise<model.ProxyQuickStatus>;

export function UninstallVersion(arg1:string,arg2:string):Promise<void>;

export function UnuseVersion(arg1:string):Promise<string>;

export function UseCustomSdk(arg1:string,arg2:string):Promise<string>;

export function UseVersion(arg1:string,arg2:string):Promise<string>;
